name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Set env vars
        run: mv .env.example .env
      - name: ESLint
        run: npm run lint
      - name: Prettier
        run: npm run lint:prettier
      - name: "Next build"
        run: npm run build
