name: Release Exchange Rates App

on:
  pull_request:
    types: [closed]
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build

  version-bump-and-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Bump version
        id: "version"
        run: |
          npm version major
          echo "::set-output name=version::$(npm --silent get-version)"
      - name: Create release branch based on version
        run: |
          git checkout -b "release-v${{steps.version.outputs.version}}"
          git merge ${{ github.event.pull_request.head.sha }} -m "Merge pull request #${{ github.event.pull_request.number }}"

  deploy-to-vercel:
    runs-on: ubuntu-latest
    needs: version-bump-and-release
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
      - name: Login to Vercel
        run: vercel login --token ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel (release branch)
        run: vercel --prod --org ${{ secrets.VERCEL_ORG_ID }} ${{ secrets.VERCEL_PROJECT_ID }} --prerelease

  merge-release-to-master:
    runs-on: ubuntu-latest
    needs: deploy-to-vercel
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release-v${{steps.version.outputs.version}}
          fetch-depth: 1
      - name: Merge release branch to master
        run: |
          git checkout main
          git merge ${{ github.event.repository.head_sha }} -m "Merge release branch v${{steps.version.outputs.version}}"

  back-merge-master-to-develop:
    runs-on: ubuntu-latest
    needs: merge-release-to-master
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - name: Back-merge master to develop
        run: |
          git merge main -m "Back-merge master changes to develop"